import Foundation

/// Builds a standalone, dependency-free `file-search.html` page with a ranked search over
/// the file-name index produced by `HomeScanner.measureDirectory`.
///
/// Ranking model (descending):
///   1. exact match
///   2. starts-with
///   3. word-boundary match (after `/`, `.`, `-`, `_`)
///   4. substring (earlier position = higher score)
///   5. subsequence / fuzzy match (denser match = higher score)
public enum FileSearchHTMLBuilder {
    public static func buildSearchPage(
        userContext: UserContext,
        fileIndex: [String: [String]],
        inventoryLinkHref: String = "inventory.html",
        generatedAt: Date = Date()
    ) -> String {
        let totalFiles = fileIndex.values.reduce(0) { $0 + $1.count }
        let folderCount = fileIndex.count

        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        dateFormatter.timeStyle = .short
        let generatedLong = dateFormatter.string(from: generatedAt)

        let title = "File search — \(userContext.fullName)"
        let fullName = HTMLReportBuilder.escape(userContext.fullName.isEmpty ? userContext.shortName : userContext.fullName)
        let subline = HTMLReportBuilder.escape("\(userContext.shortName)@\(userContext.hostName) · \(userContext.osVersion) · \(generatedLong)")

        let indexJson = encodeJson(fileIndex)

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>\(HTMLReportBuilder.escape(title))</title>
        <style>
        \(stylesheet)
        </style>
        </head>
        <body>
        <div class="wrap">
          <header class="hero">
            <h1>File search</h1>
            <p class="sub">\(fullName) — \(subline)</p>
            <p class="back"><a href="\(HTMLReportBuilder.escape(inventoryLinkHref))">← Back to migration report</a></p>
          </header>

          <section>
            <input id="q" type="search" autocomplete="off" autofocus
              placeholder="Type at least 2 characters — try: Package.swift, .env, node_modules"/>
            <p class="hint">Indexed <strong>\(totalFiles)</strong> file name(s) across <strong>\(folderCount)</strong> selected folder(s).</p>
            <p id="status" class="muted"></p>
            <div id="results"></div>
          </section>

          <footer>Generated by DriveScanner on \(HTMLReportBuilder.escape(generatedLong)) · Search runs entirely in your browser; no data is sent anywhere.</footer>
        </div>
        <script id="file-index" type="application/json">\(indexJson)</script>
        <script>
        \(searchScript)
        </script>
        </body>
        </html>
        """
    }

    // MARK: - JSON encoding

    private static func encodeJson(_ value: [String: [String]]) -> String {
        guard let data = try? JSONSerialization.data(withJSONObject: value, options: []) else { return "{}" }
        let raw = String(data: data, encoding: .utf8) ?? "{}"
        return raw
            .replacingOccurrences(of: "</", with: "<\\/")
            .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
            .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
    }

    // MARK: - Static assets

    private static let stylesheet: String = """
    :root {
      color-scheme: light dark;
      --bg: #f5f5f7;
      --card: #ffffff;
      --text: #1d1d1f;
      --muted: #6e6e73;
      --border: #d2d2d7;
      --accent: #0071e3;
      --accent-2: #5e5ce6;
      --hl: rgba(255, 220, 0, 0.55);
      --row-alt: #fafafa;
      --shadow: 0 1px 2px rgba(0,0,0,0.04), 0 2px 8px rgba(0,0,0,0.04);
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #1c1c1e;
        --card: #2c2c2e;
        --text: #f5f5f7;
        --muted: #98989f;
        --border: #3a3a3c;
        --accent: #0a84ff;
        --accent-2: #5e5ce6;
        --hl: rgba(255, 200, 0, 0.35);
        --row-alt: #262628;
        --shadow: 0 1px 2px rgba(0,0,0,0.5), 0 2px 10px rgba(0,0,0,0.35);
      }
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", system-ui, sans-serif;
      margin: 0;
      padding: 2rem clamp(1rem, 5vw, 3rem) 4rem;
      background: var(--bg);
      color: var(--text);
      line-height: 1.5;
      font-size: 15px;
      -webkit-font-smoothing: antialiased;
    }
    .wrap { max-width: 1080px; margin: 0 auto; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    .hero {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 1.25rem 1.5rem;
      margin-bottom: 1.5rem;
      box-shadow: var(--shadow);
    }
    .hero h1 { margin: 0 0 0.25rem; font-size: 1.4rem; font-weight: 650; letter-spacing: -0.01em; }
    .hero .sub { margin: 0; color: var(--muted); font-size: 0.9rem; }
    .hero .back { margin: 0.5rem 0 0; font-size: 0.85rem; }
    section {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 1.25rem 1.5rem 1.5rem;
      margin-bottom: 1.25rem;
      box-shadow: var(--shadow);
    }
    input[type="search"] {
      width: 100%;
      padding: 0.75rem 1rem;
      font-size: 1rem;
      border: 1px solid var(--border);
      border-radius: 10px;
      background: var(--bg);
      color: var(--text);
      font-family: inherit;
    }
    input[type="search"]:focus {
      outline: 2px solid var(--accent);
      outline-offset: -1px;
      border-color: var(--accent);
    }
    .hint { color: var(--muted); font-size: 0.85rem; margin: 0.6rem 0 0; }
    #status { font-size: 0.8rem; margin: 0.5rem 0 0; }
    #results { margin-top: 0.85rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
    th, td {
      padding: 0.55rem 0.65rem;
      text-align: left;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }
    thead th {
      font-weight: 600;
      color: var(--muted);
      font-size: 0.72rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    tbody tr:hover { background: var(--row-alt); }
    tbody tr:last-child td { border-bottom: none; }
    .file-cell { font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace; font-size: 0.85rem; }
    .folder-cell {
      color: var(--muted);
      font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
      font-size: 0.78rem;
      word-break: break-all;
    }
    .score { color: var(--muted); font-size: 0.75rem; font-variant-numeric: tabular-nums; }
    mark { background: var(--hl); color: inherit; padding: 0 1px; border-radius: 2px; }
    .muted { color: var(--muted); }
    footer {
      color: var(--muted);
      font-size: 0.8rem;
      text-align: center;
      margin-top: 1.5rem;
    }
    """

    private static let searchScript: String = """
    (function() {
      var indexEl = document.getElementById('file-index');
      var input = document.getElementById('q');
      var resultsEl = document.getElementById('results');
      var statusEl = document.getElementById('status');
      if (!indexEl || !input || !resultsEl) return;

      var INDEX = {};
      try { INDEX = JSON.parse(indexEl.textContent || '{}'); } catch (e) { INDEX = {}; }

      var FLAT = [];
      for (var folder in INDEX) {
        if (!Object.prototype.hasOwnProperty.call(INDEX, folder)) continue;
        var files = INDEX[folder];
        for (var i = 0; i < files.length; i++) {
          var name = files[i];
          FLAT.push({ file: name, fileLower: name.toLowerCase(), folder: folder });
        }
      }
      statusEl.textContent = 'Ready. ' + FLAT.length + ' file name(s) indexed.';

      var debounceTimer;
      input.addEventListener('input', function() {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(runSearch, 80);
      });

      function runSearch() {
        var raw = (input.value || '').trim();
        if (raw.length < 2) {
          resultsEl.innerHTML = '';
          statusEl.textContent = FLAT.length + ' file name(s) indexed.';
          return;
        }
        var q = raw.toLowerCase();
        var t0 = performance.now ? performance.now() : Date.now();
        var hits = [];
        var limit = 200;
        for (var i = 0; i < FLAT.length; i++) {
          var entry = FLAT[i];
          var s = score(q, entry.fileLower);
          if (s > 0) {
            hits.push({ entry: entry, score: s });
          }
        }
        hits.sort(function(a, b) { return b.score - a.score; });
        var capped = hits.length > limit;
        hits = hits.slice(0, limit);
        var t1 = performance.now ? performance.now() : Date.now();
        statusEl.textContent = hits.length + (capped ? '+' : '') + ' match(es) in ' + (t1 - t0).toFixed(0) + ' ms';
        renderHits(hits, raw);
      }

      function score(q, t) {
        if (t === q) return 1000;
        if (t.indexOf(q) === 0) return 900 - Math.min(99, t.length - q.length);
        var sep = '/.-_';
        for (var i = 0; i < t.length - q.length; i++) {
          if (sep.indexOf(t.charAt(i)) >= 0 && t.substr(i + 1, q.length) === q) {
            return 800 - Math.min(99, i);
          }
        }
        var idx = t.indexOf(q);
        if (idx >= 0) return 700 - Math.min(99, idx);
        var qi = 0, lastMatch = -1, gaps = 0;
        for (var ti = 0; ti < t.length && qi < q.length; ti++) {
          if (t.charAt(ti) === q.charAt(qi)) {
            if (lastMatch >= 0) gaps += ti - lastMatch - 1;
            lastMatch = ti;
            qi++;
          }
        }
        if (qi === q.length) {
          return Math.max(100, 500 - gaps - Math.min(200, t.length - q.length));
        }
        return 0;
      }

      function renderHits(hits, q) {
        if (hits.length === 0) {
          resultsEl.innerHTML = '<p class="muted">No matches.</p>';
          return;
        }
        var rows = '';
        for (var i = 0; i < hits.length; i++) {
          var e = hits[i].entry;
          rows += '<tr><td class="file-cell">' + highlight(e.file, q) +
                  '</td><td class="folder-cell">' + esc(e.folder) +
                  '</td><td class="score">' + hits[i].score + '</td></tr>';
        }
        resultsEl.innerHTML =
          '<table><thead><tr><th>File</th><th>Folder</th><th class="score">Score</th></tr></thead><tbody>' +
          rows + '</tbody></table>';
      }

      function highlight(text, q) {
        var t = text.toLowerCase();
        var ql = q.toLowerCase();
        var idx = t.indexOf(ql);
        if (idx < 0) return esc(text);
        return esc(text.slice(0, idx)) + '<mark>' + esc(text.slice(idx, idx + q.length)) + '</mark>' + esc(text.slice(idx + q.length));
      }

      function esc(s) {
        return String(s).replace(/[&<>"']/g, function(c) {
          return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
        });
      }
    })();
    """
}
