import Foundation

/// Builds a single self-contained, user-branded HTML migration report.
public enum HTMLReportBuilder {
    public static func buildReport(
        userContext: UserContext,
        selectedItems: [CandidateItem],
        excludedItems: [CandidateItem],
        rollup: FolderRollupResult,
        mediaMeasurements: [MediaFolderMeasurement],
        homebrew: HomebrewInfo?,
        fileIndex: [String: [String]] = [:],
        generatedAt: Date = Date()
    ) -> String {
        let totalSelectedBytes = selectedItems.reduce(Int64(0)) { $0 + $1.sizeBytes }
        let mediaTotalBytes = mediaMeasurements.reduce(Int64(0)) { $0 + (($1.exists ? $1.totalBytes : 0)) }
        let devConfigCount = selectedItems.filter { $0.category == .devConfig }.count
        let projectCount = selectedItems.filter { $0.category == .codeProject }.count

        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        dateFormatter.timeStyle = .short
        let generatedLong = dateFormatter.string(from: generatedAt)

        let hero = renderHero(
            userContext: userContext,
            selectedCount: selectedItems.count,
            totalSelectedBytes: totalSelectedBytes,
            mediaTotalBytes: mediaTotalBytes,
            devConfigCount: devConfigCount,
            projectCount: projectCount,
            homebrew: homebrew,
            generatedLong: generatedLong
        )
        let searchSection = renderSearchSection(fileIndex: fileIndex)
        let included = renderItems(title: "Folders to migrate", items: selectedItems, isExcluded: false, emptyMessage: "No items selected.")
        let breakdown = renderBreakdown(rollup)
        let brewSection = renderHomebrew(homebrew)
        let media = renderMedia(mediaMeasurements)
        let excluded = excludedItems.isEmpty
            ? ""
            : renderItems(title: "Excluded (not migrating)", items: excludedItems, isExcluded: true, emptyMessage: "")

        let fileIndexJson = encodeJson(fileIndex)
        let title = "Migration report — \(userContext.fullName)"

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>\(escape(title))</title>
        <style>
        \(stylesheet)
        </style>
        </head>
        <body>
        <div class="wrap">
        \(hero)
        \(searchSection)
        \(included)
        \(breakdown)
        \(brewSection)
        \(media)
        \(excluded)
        <footer>Generated by DriveScanner on \(escape(generatedLong))</footer>
        </div>
        <script id="file-index" type="application/json">\(fileIndexJson)</script>
        <script>
        \(reportScript)
        </script>
        </body>
        </html>
        """
    }

    private static func encodeJson(_ value: [String: [String]]) -> String {
        guard let data = try? JSONSerialization.data(withJSONObject: value, options: []) else { return "{}" }
        let raw = String(data: data, encoding: .utf8) ?? "{}"
        // Prevent `</script>` injection inside the embedded JSON.
        return raw
            .replacingOccurrences(of: "</", with: "<\\/")
            .replacingOccurrences(of: "\u{2028}", with: "\\u2028")
            .replacingOccurrences(of: "\u{2029}", with: "\\u2029")
    }

    private static func renderSearchSection(fileIndex: [String: [String]]) -> String {
        if fileIndex.isEmpty {
            return ""
        }
        let totalFiles = fileIndex.values.reduce(0) { $0 + $1.count }
        return """
        <section id="search-section">
          <h2>Search files inside selected folders</h2>
          <p class="muted" style="margin:0 0 0.65rem;">Indexed \(totalFiles) file name(s) across \(fileIndex.count) folder(s). Type at least 2 characters.</p>
          <input id="globalSearch" type="search" placeholder="e.g. Package.swift, .env, config.json" autocomplete="off"/>
          <div id="searchResults"></div>
        </section>
        """
    }

    public static func escape(_ s: String) -> String {
        var out = ""
        out.reserveCapacity(s.count)
        for ch in s.unicodeScalars {
            switch ch {
            case "&": out.append("&amp;")
            case "<": out.append("&lt;")
            case ">": out.append("&gt;")
            case "\"": out.append("&quot;")
            case "'": out.append("&#39;")
            default:
                if ch.value < 32 || ch.value == 0x7F {
                    out.append("&#\(ch.value);")
                } else {
                    out.unicodeScalars.append(ch)
                }
            }
        }
        return out
    }

    // MARK: - Sections

    private static func renderHero(
        userContext: UserContext,
        selectedCount: Int,
        totalSelectedBytes: Int64,
        mediaTotalBytes: Int64,
        devConfigCount: Int,
        projectCount: Int,
        homebrew: HomebrewInfo?,
        generatedLong: String
    ) -> String {
        let initials = escape(userContext.initials)
        let fullName = escape(userContext.fullName.isEmpty ? userContext.shortName : userContext.fullName)
        let subline = escape("\(userContext.shortName)@\(userContext.hostName) · \(userContext.osVersion) · \(generatedLong)")
        let sizeStr = escape(formatBytes(totalSelectedBytes))
        let mediaStr = escape(formatBytes(mediaTotalBytes))
        let brewKpi: String
        if let h = homebrew, !h.isEmpty {
            brewKpi = """
            <div class="kpi"><span class="kpi-label">Homebrew</span><span class="kpi-value">\(h.formulaCount + h.caskCount)</span><span class="kpi-sub">formulae + casks</span></div>
            """
        } else {
            brewKpi = """
            <div class="kpi"><span class="kpi-label">Homebrew</span><span class="kpi-value">—</span><span class="kpi-sub">not detected</span></div>
            """
        }

        return """
        <header class="hero">
          <div class="hero-top">
            <div class="avatar">\(initials)</div>
            <div>
              <h1>\(fullName)</h1>
              <p class="sub">\(subline)</p>
            </div>
          </div>
          <div class="kpis">
            <div class="kpi"><span class="kpi-label">Selected to migrate</span><span class="kpi-value">\(selectedCount)</span><span class="kpi-sub">items</span></div>
            <div class="kpi"><span class="kpi-label">Total size</span><span class="kpi-value">\(sizeStr)</span><span class="kpi-sub">allocated on disk</span></div>
            <div class="kpi"><span class="kpi-label">Code projects</span><span class="kpi-value">\(projectCount)</span><span class="kpi-sub">detected</span></div>
            <div class="kpi"><span class="kpi-label">Dev configs</span><span class="kpi-value">\(devConfigCount)</span><span class="kpi-sub">dotfiles</span></div>
            \(brewKpi)
            <div class="kpi"><span class="kpi-label">Media folders</span><span class="kpi-value">\(mediaStr)</span><span class="kpi-sub">pictures + music + movies</span></div>
          </div>
        </header>
        """
    }

    private static func renderItems(title: String, items: [CandidateItem], isExcluded: Bool, emptyMessage: String) -> String {
        let sectionClass = isExcluded ? "section-excluded" : ""
        if items.isEmpty {
            if emptyMessage.isEmpty { return "" }
            return """
            <section class="\(sectionClass)">
              <h2>\(escape(title))</h2>
              <p class="empty">\(escape(emptyMessage))</p>
            </section>
            """
        }

        let modFormatter = DateFormatter()
        modFormatter.dateStyle = .medium
        modFormatter.timeStyle = .none

        let rows = items
            .sorted { $0.sizeBytes > $1.sizeBytes }
            .map { item -> String in
                let catTag = """
                <span class="tag \(item.category.tagClass)">\(escape(item.category.displayLabel.uppercased()))</span>
                """
                let stackTag: String = item.stack.map {
                    "<span class=\"tag tag-stack\">\(escape($0.displayLabel.uppercased()))</span>"
                } ?? ""
                let symTag = item.isSymlink ? "<span class=\"tag tag-warn\">SYMLINK</span>" : ""
                let fileTag = (!item.isDirectory && !item.isSymlink) ? "<span class=\"tag tag-file\">FILE</span>" : ""
                let modStr = item.modificationDate.map { modFormatter.string(from: $0) } ?? "—"
                return """
                <tr>
                  <td>
                    <div class="row-name">\(escape(item.name))</div>
                    <div class="row-tags">\(catTag)\(stackTag)\(symTag)\(fileTag)</div>
                  </td>
                  <td class="path">\(escape(displayPath(item.url)))</td>
                  <td class="num">\(escape(formatBytes(item.sizeBytes)))</td>
                  <td>\(escape(modStr))</td>
                </tr>
                """
            }
            .joined(separator: "\n")

        return """
        <section class="\(sectionClass)">
          <h2>\(escape(title)) <span class="section-count">(\(items.count))</span></h2>
          <table class="sortable">
            <thead><tr><th>Name</th><th>Path</th><th class="num">Size</th><th>Modified</th></tr></thead>
            <tbody>
        \(rows)
            </tbody>
          </table>
        </section>
        """
    }

    private static func renderBreakdown(_ rollup: FolderRollupResult) -> String {
        let nonEmpty = rollup.perRoot.filter { !$0.depth1.isEmpty || !$0.looseFiles.isEmpty }
        guard !nonEmpty.isEmpty else { return "" }

        let articles = nonEmpty.map { per -> String in
            let name = escape(per.rootDisplayName)
            var blocks: [String] = ["<h3>\(name)</h3>"]
            if !per.depth1.isEmpty {
                blocks.append(renderBucketTable(title: "Top sub-folders", buckets: per.depth1))
            }
            if !per.looseFiles.isEmpty {
                blocks.append(renderBucketTable(title: "Loose files at root", buckets: per.looseFiles))
            }
            return blocks.joined(separator: "\n")
        }.joined(separator: "\n")

        return """
        <section>
          <h2>Inside each selected folder</h2>
        \(articles)
        </section>
        """
    }

    private static func renderBucketTable(title: String, buckets: [FolderRollupBucket]) -> String {
        let rows = buckets.map { bucket -> String in
            return """
            <tr>
              <td>\(escape(bucket.label))</td>
              <td class="num">\(bucket.fileCount)</td>
              <td class="num">\(escape(formatBytes(bucket.totalBytes)))</td>
            </tr>
            """
        }.joined(separator: "\n")

        return """
        <p class="bucket-title">\(escape(title))</p>
        <table>
          <thead><tr><th>Sub-folder</th><th class="num">Files</th><th class="num">Size</th></tr></thead>
          <tbody>
        \(rows)
          </tbody>
        </table>
        """
    }

    private static func renderHomebrew(_ info: HomebrewInfo?) -> String {
        guard let info, !info.isEmpty else { return "" }
        let restoreCmd = HomebrewService.restoreCommand()
        let escapedBrewfile = escape(info.brewfile)

        return """
        <section>
          <h2>Homebrew</h2>
          <p class="muted" style="margin:0 0 0.75rem;">Detected at <code>\(escape(info.brewPath))</code></p>
          <div class="kpis kpis-inline">
            <div class="kpi"><span class="kpi-label">Formulae</span><span class="kpi-value">\(info.formulaCount)</span></div>
            <div class="kpi"><span class="kpi-label">Casks</span><span class="kpi-value">\(info.caskCount)</span></div>
            <div class="kpi"><span class="kpi-label">Taps</span><span class="kpi-value">\(info.tapCount)</span></div>
            <div class="kpi"><span class="kpi-label">Mac App Store</span><span class="kpi-value">\(info.masCount)</span></div>
          </div>
          <h3>Restore on the new Mac</h3>
          <ol class="steps">
            <li>Install Homebrew: <code>/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"</code></li>
            <li>Copy the <code>Brewfile</code> from your migration bundle to the new Mac.</li>
            <li>Run <code>\(escape(restoreCmd))</code> from the folder containing the Brewfile.</li>
          </ol>
          <details class="brewfile">
            <summary>View Brewfile (\(info.totalItems) entries)</summary>
            <pre>\(escapedBrewfile)</pre>
          </details>
        </section>
        """
    }

    private static func renderMedia(_ measurements: [MediaFolderMeasurement]) -> String {
        guard !measurements.isEmpty else { return "" }
        let rows = measurements.map { m -> String in
            let sizeCell = m.exists ? escape(formatBytes(m.totalBytes)) : "<span class=\"muted\">not found</span>"
            return """
            <tr>
              <td>\(escape(m.folder.displayLabel))</td>
              <td class="path">~/\(escape(m.folder.directoryName))</td>
              <td class="num">\(sizeCell)</td>
            </tr>
            """
        }.joined(separator: "\n")

        return """
        <section>
          <h2>Standard media folders</h2>
          <table>
            <thead><tr><th>Folder</th><th>Path</th><th class="num">Size</th></tr></thead>
            <tbody>
        \(rows)
            </tbody>
          </table>
        </section>
        """
    }

    // MARK: - Helpers

    private static func formatBytes(_ bytes: Int64) -> String {
        ByteCountFormatter.string(fromByteCount: bytes, countStyle: .file)
    }

    private static func displayPath(_ url: URL) -> String {
        let home = NSHomeDirectory()
        let p = url.path
        if p.hasPrefix(home) {
            return "~" + p.dropFirst(home.count)
        }
        return p
    }

    private static let stylesheet: String = """
    :root {
      color-scheme: light dark;
      --bg: #f5f5f7;
      --card: #ffffff;
      --text: #1d1d1f;
      --muted: #6e6e73;
      --border: #d2d2d7;
      --accent: #0071e3;
      --accent-2: #5e5ce6;
      --warn: #b25000;
      --row-alt: #fafafa;
      --shadow: 0 1px 2px rgba(0,0,0,0.04), 0 2px 8px rgba(0,0,0,0.04);
      --excluded-bg: #f0f0f2;
      --code-bg: #f3f3f5;
      --color-project: #1b8a52;
      --color-personal: #0071e3;
      --color-config: #8e44ad;
      --color-file: #6e6e73;
      --color-stack: #b25000;
    }
    @media (prefers-color-scheme: dark) {
      :root {
        --bg: #1c1c1e;
        --card: #2c2c2e;
        --text: #f5f5f7;
        --muted: #98989f;
        --border: #3a3a3c;
        --accent: #0a84ff;
        --accent-2: #5e5ce6;
        --warn: #ff9f0a;
        --row-alt: #262628;
        --shadow: 0 1px 2px rgba(0,0,0,0.5), 0 2px 10px rgba(0,0,0,0.35);
        --excluded-bg: #232325;
        --code-bg: #1a1a1c;
        --color-project: #30d158;
        --color-personal: #0a84ff;
        --color-config: #bf5af2;
        --color-file: #98989f;
        --color-stack: #ff9f0a;
      }
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", system-ui, sans-serif;
      margin: 0;
      padding: 2rem clamp(1rem, 5vw, 3rem) 4rem;
      background: var(--bg);
      color: var(--text);
      line-height: 1.5;
      font-size: 15px;
      -webkit-font-smoothing: antialiased;
    }
    .wrap { max-width: 1080px; margin: 0 auto; }
    code {
      font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
      font-size: 0.85em;
      background: var(--code-bg);
      padding: 0.1rem 0.35rem;
      border-radius: 4px;
      word-break: break-all;
    }
    pre {
      font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
      font-size: 0.78rem;
      line-height: 1.45;
      background: var(--code-bg);
      padding: 0.85rem 1rem;
      border-radius: 8px;
      overflow-x: auto;
      margin: 0.5rem 0 0;
      max-height: 28rem;
    }
    .hero {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 1.5rem 1.75rem;
      margin-bottom: 1.5rem;
      box-shadow: var(--shadow);
    }
    .hero-top { display: flex; align-items: center; gap: 1rem; margin-bottom: 1.25rem; }
    .avatar {
      width: 56px; height: 56px;
      border-radius: 50%;
      background: linear-gradient(135deg, var(--accent), var(--accent-2));
      color: white;
      display: flex; align-items: center; justify-content: center;
      font-weight: 600; font-size: 1.25rem;
      flex-shrink: 0;
      letter-spacing: 0.02em;
    }
    .hero h1 { margin: 0; font-size: 1.5rem; font-weight: 650; letter-spacing: -0.01em; }
    .hero .sub { margin: 0.15rem 0 0; color: var(--muted); font-size: 0.9rem; }
    .kpis {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 0.75rem;
    }
    .kpis-inline { grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); margin-bottom: 1rem; }
    .kpi {
      background: var(--bg);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 0.75rem 0.9rem;
    }
    .kpi-label {
      display: block;
      color: var(--muted);
      font-size: 0.7rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 0.2rem;
    }
    .kpi-value {
      display: block;
      font-size: 1.25rem;
      font-weight: 600;
      font-variant-numeric: tabular-nums;
      letter-spacing: -0.01em;
    }
    .kpi-sub {
      display: block;
      color: var(--muted);
      font-size: 0.7rem;
      margin-top: 0.1rem;
    }
    section {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 14px;
      padding: 1.25rem 1.5rem 1.5rem;
      margin-bottom: 1.25rem;
      box-shadow: var(--shadow);
    }
    section.section-excluded {
      background: var(--excluded-bg);
      opacity: 0.78;
    }
    section h2 {
      font-size: 1.05rem;
      font-weight: 650;
      letter-spacing: -0.01em;
      margin: 0 0 1rem;
    }
    .section-count {
      font-size: 0.85rem;
      font-weight: 500;
      color: var(--muted);
    }
    section h3 {
      font-size: 0.95rem;
      font-weight: 600;
      margin: 1.5rem 0 0.5rem;
      color: var(--text);
    }
    section h3:first-of-type { margin-top: 0; }
    .bucket-title {
      margin: 0.75rem 0 0.35rem;
      font-size: 0.72rem;
      font-weight: 600;
      color: var(--muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    .muted { color: var(--muted); }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.875rem;
    }
    th, td {
      padding: 0.55rem 0.65rem;
      text-align: left;
      border-bottom: 1px solid var(--border);
      vertical-align: top;
    }
    thead th {
      font-weight: 600;
      color: var(--muted);
      font-size: 0.72rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    table.sortable thead th {
      cursor: pointer;
      user-select: none;
      position: relative;
      padding-right: 1.1rem;
    }
    table.sortable thead th:hover { color: var(--text); }
    table.sortable thead th[data-dir="asc"]::after {
      content: " ▲";
      color: var(--accent);
      font-size: 0.65rem;
      position: absolute;
      right: 0.3rem;
    }
    table.sortable thead th[data-dir="desc"]::after {
      content: " ▼";
      color: var(--accent);
      font-size: 0.65rem;
      position: absolute;
      right: 0.3rem;
    }
    #search-section input[type="search"] {
      width: 100%;
      padding: 0.6rem 0.85rem;
      font-size: 0.95rem;
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--bg);
      color: var(--text);
      font-family: inherit;
      box-sizing: border-box;
    }
    #search-section input[type="search"]:focus {
      outline: 2px solid var(--accent);
      outline-offset: -1px;
      border-color: var(--accent);
    }
    #searchResults { margin-top: 0.85rem; }
    #searchResults table { font-size: 0.82rem; }
    .search-hits-summary {
      color: var(--muted);
      font-size: 0.78rem;
      margin: 0 0 0.4rem;
    }
    tbody tr:hover { background: var(--row-alt); }
    tbody tr:last-child td { border-bottom: none; }
    td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
    td.path {
      color: var(--muted);
      font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
      font-size: 0.78rem;
      word-break: break-all;
    }
    .row-name { font-weight: 500; }
    .row-tags { margin-top: 0.2rem; display: flex; flex-wrap: wrap; gap: 0.25rem; }
    .tag {
      display: inline-block;
      padding: 0.08rem 0.42rem;
      border-radius: 4px;
      font-size: 0.62rem;
      font-weight: 700;
      color: white;
      letter-spacing: 0.05em;
      line-height: 1.4;
    }
    .tag-project { background: var(--color-project); }
    .tag-personal { background: var(--color-personal); }
    .tag-config { background: var(--color-config); }
    .tag-file { background: var(--color-file); }
    .tag-stack { background: var(--color-stack); }
    .tag-warn { background: var(--warn); }
    .empty {
      color: var(--muted);
      font-style: italic;
      padding: 0.5rem 0;
    }
    .steps {
      padding-left: 1.25rem;
      margin: 0.25rem 0 1rem;
    }
    .steps li {
      margin-bottom: 0.4rem;
      line-height: 1.55;
    }
    details.brewfile { margin-top: 0.5rem; }
    details.brewfile > summary {
      cursor: pointer;
      font-weight: 500;
      color: var(--accent);
      padding: 0.35rem 0;
      list-style-position: outside;
    }
    footer {
      color: var(--muted);
      font-size: 0.8rem;
      text-align: center;
      margin-top: 1.5rem;
    }
    @media print {
      body { background: white; padding: 1rem; }
      section, .hero { box-shadow: none; }
      details.brewfile[open] pre { max-height: none; }
    }
    """

    private static let reportScript: String = """
    (function() {
      // ---- Sortable tables ----
      document.querySelectorAll('table.sortable').forEach(function(table) {
        var headers = table.querySelectorAll('thead th');
        headers.forEach(function(th, idx) {
          th.addEventListener('click', function() {
            sortColumn(table, idx, th);
          });
        });
      });

      function sortColumn(table, idx, th) {
        var tbody = table.querySelector('tbody');
        var rows = Array.prototype.slice.call(tbody.querySelectorAll('tr'));
        var isNum = th.classList.contains('num');
        var current = th.getAttribute('data-dir');
        var ascending = current !== 'asc';
        table.querySelectorAll('thead th').forEach(function(h) { h.removeAttribute('data-dir'); });
        th.setAttribute('data-dir', ascending ? 'asc' : 'desc');
        rows.sort(function(a, b) {
          var av = a.cells[idx] ? a.cells[idx].textContent.trim() : '';
          var bv = b.cells[idx] ? b.cells[idx].textContent.trim() : '';
          var cmp;
          if (isNum) {
            cmp = parseBytes(av) - parseBytes(bv);
          } else {
            // Date column ("16 May 2026") fallback to string compare — good enough for same-locale exports
            cmp = av.localeCompare(bv, undefined, { numeric: true, sensitivity: 'base' });
          }
          return ascending ? cmp : -cmp;
        });
        rows.forEach(function(r) { tbody.appendChild(r); });
      }

      function parseBytes(text) {
        if (!text) return 0;
        var m = text.match(/([\\d.,]+)\\s*(bytes|B|KB|MB|GB|TB|PB|Zero)/i);
        if (!m) {
          var n = parseFloat(text.replace(/,/g, ''));
          return isNaN(n) ? 0 : n;
        }
        if (m[2] && m[2].toLowerCase() === 'zero') return 0;
        var num = parseFloat(m[1].replace(/,/g, ''));
        var unit = (m[2] || 'B').toLowerCase();
        var mult = { 'bytes': 1, 'b': 1, 'kb': 1000, 'mb': 1000000, 'gb': 1000000000, 'tb': 1000000000000, 'pb': 1000000000000000 };
        return num * (mult[unit] || 1);
      }

      // ---- Global file search ----
      var indexEl = document.getElementById('file-index');
      var input = document.getElementById('globalSearch');
      var resultsEl = document.getElementById('searchResults');
      if (!indexEl || !input || !resultsEl) return;
      var INDEX = {};
      try { INDEX = JSON.parse(indexEl.textContent || '{}'); } catch (e) { INDEX = {}; }

      var debounceTimer;
      input.addEventListener('input', function() {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(runSearch, 80);
      });

      function runSearch() {
        var q = (input.value || '').trim().toLowerCase();
        if (q.length < 2) {
          resultsEl.innerHTML = '';
          return;
        }
        var hits = [];
        var limit = 200;
        outer: for (var folder in INDEX) {
          if (!Object.prototype.hasOwnProperty.call(INDEX, folder)) continue;
          var files = INDEX[folder];
          for (var i = 0; i < files.length; i++) {
            if (files[i].toLowerCase().indexOf(q) !== -1) {
              hits.push({ folder: folder, file: files[i] });
              if (hits.length >= limit) break outer;
            }
          }
        }
        if (hits.length === 0) {
          resultsEl.innerHTML = '<p class="search-hits-summary">No matches.</p>';
          return;
        }
        var html = '<p class="search-hits-summary">' + hits.length + (hits.length >= limit ? '+' : '') + ' match(es)</p>';
        html += '<table><thead><tr><th>File</th><th>Folder</th></tr></thead><tbody>';
        for (var h = 0; h < hits.length; h++) {
          html += '<tr><td>' + esc(hits[h].file) + '</td><td>' + esc(hits[h].folder) + '</td></tr>';
        }
        html += '</tbody></table>';
        resultsEl.innerHTML = html;
      }

      function esc(s) {
        return String(s).replace(/[&<>"']/g, function(c) {
          return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
        });
      }
    })();
    """
}
